# Generated by Django 4.2 on 2023-04-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="from_city",
            field=models.CharField(default="Chennai", max_length=100),
        ),
        migrations.AddField(
            model_name="flight",
            name="to_city",
            field=models.CharField(default="Kanpur", max_length=100),
        ),
    ]
